name: Trigger auto deployment for usr17ka-my-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/usr17ka-my-container-app-AutoDeployTrigger-5a26ae67-6114-479c-9b0a-2d5a34b6fd47.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.USR17KAMYCONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: usr17kacontainerregistry.azurecr.io
          registryUsername: ${{ secrets.USR17KAMYCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.USR17KAMYCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: usr17ka-my-container-app
          resourceGroup: usr17Krg-my-container-apps
          imageToBuild: usr17kacontainerregistry.azurecr.io/usr17ka-my-container-app:${{ github.sha }}
          
            

     

